name: personalized-news-backend
region: fra

# Backend Service (Node.js API)
services:
  - name: backend
    source_dir: backend
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      - key: PORT
        value: "3000"
        scope: RUN_TIME
      - key: SUPABASE_URL
        value: ${SUPABASE_URL}
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: ${SUPABASE_SERVICE_ROLE_KEY}
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        value: ${JWT_SECRET}
        scope: RUN_TIME
        type: SECRET
      - key: GUARDIAN_API_KEY
        value: ${GUARDIAN_API_KEY}
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGINS
        value: ${CORS_ORIGINS}
        scope: RUN_TIME
        type: SECRET

